package auth_test

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/danielvm/bigbase/components/auth"
	"github.com/danielvm/bigbase/components/db"
	"github.com/danielvm/bigbase/kernel"
)

// --- e50s01: JWT Secret resolution ---

func TestJWTSecretFromEnv(t *testing.T) {
	t.Setenv("BIGBASE_JWT_SECRET", "")
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	// opts.Secret takes priority: env-based resolution is bypassed.
	a := auth.New(auth.Options{DB: d, Logger: logger, Secret: "test-secret-32-chars!!!"})
	k := kernel.New(logger)
	k.Register(d)
	k.Register(a)
	if err := k.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	defer func() { _ = k.Stop() }()
}

func TestJWTSecretEnvVarUsed(t *testing.T) {
	secret := "a-proper-secret-with-at-least-32-bytes-here"
	t.Setenv("BIGBASE_JWT_SECRET", secret)
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	// opts.Secret empty → resolveJWTSecret reads env var
	a := auth.New(auth.Options{DB: d, Logger: logger})
	k := kernel.New(logger)
	k.Register(d)
	k.Register(a)
	if err := k.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	defer func() { _ = k.Stop() }()

	// Register and login should work (env secret is valid).
	h := a.Handler()
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"secretenv@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: expected 201, got %d: %s", regW.Code, regW.Body.String())
	}
}

func TestJWTSecretTooShortPanics(t *testing.T) {
	t.Setenv("BIGBASE_JWT_SECRET", "short")
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected panic for short secret, got none")
		} else {
			str, ok := r.(string)
			if !ok || !strings.Contains(str, "must be at least 32 bytes") {
				t.Fatalf("expected panic containing 'must be at least 32 bytes', got: %v", r)
			}
		}
	}()
	auth.New(auth.Options{DB: d, Logger: logger})
}

func TestJWTSecretKnownDefaultPanics(t *testing.T) {
	// Use a known-default string that is >= 32 bytes but is in the blocklist.
	t.Setenv("BIGBASE_JWT_SECRET", "test-secret-32-chars-long-key!!!")
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected panic for known default secret, got none")
		} else {
			str, ok := r.(string)
			if !ok || !strings.Contains(str, "known default") {
				t.Fatalf("expected panic containing 'known default', got: %v", r)
			}
		}
	}()
	auth.New(auth.Options{DB: d, Logger: logger})
}

func TestProgrammaticSecretValidation(t *testing.T) {
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})

	// With test mode enabled (default), invalid programmatic secrets should NOT panic.
	_ = auth.New(auth.Options{DB: d, Logger: logger, Secret: "short"})
	_ = auth.New(auth.Options{DB: d, Logger: logger, Secret: "test-secret-32-chars-long-key!!!"})

	// Disable test mode temporarily to trigger validation panic on programmatic secrets.
	auth.ResetTestModeForTesting(false)
	defer auth.ResetTestModeForTesting(true)

	t.Run("too short secret", func(t *testing.T) {
		defer func() {
			if r := recover(); r == nil {
				t.Fatal("expected panic for short programmatic secret, got none")
			} else {
				str, ok := r.(string)
				if !ok || !strings.Contains(str, "must be at least 32 bytes") {
					t.Fatalf("expected panic containing 'must be at least 32 bytes', got: %v", r)
				}
			}
		}()
		auth.New(auth.Options{DB: d, Logger: logger, Secret: "short"})
	})

	t.Run("known default secret", func(t *testing.T) {
		defer func() {
			if r := recover(); r == nil {
				t.Fatal("expected panic for known default programmatic secret, got none")
			} else {
				str, ok := r.(string)
				if !ok || !strings.Contains(str, "known default") {
					t.Fatalf("expected panic containing 'known default', got: %v", r)
				}
			}
		}()
		auth.New(auth.Options{DB: d, Logger: logger, Secret: "test-secret-32-chars-long-key!!!"})
	})
}


func TestJWTSecretAutoGeneratedWhenEnvUnset(t *testing.T) {
	t.Setenv("BIGBASE_JWT_SECRET", "")
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	// No Secret, no env var → auto-generate (should not panic).
	a := auth.New(auth.Options{DB: d, Logger: logger})
	k := kernel.New(logger)
	k.Register(d)
	k.Register(a)
	if err := k.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	defer func() { _ = k.Stop() }()
}

// --- e50s02: Configurable token lifetimes ---

func setupAuthWithExpiry(t *testing.T, access, refresh time.Duration) (*auth.Auth, http.Handler, http.Handler) {
	t.Helper()
	logger := testLogger{}
	d := db.New(db.Options{Path: ":memory:", Logger: logger})
	a := auth.New(auth.Options{
		DB:            d,
		Logger:        logger,
		Secret:        "test-secret-32-chars!!!",
		AccessExpiry:  access,
		RefreshExpiry: refresh,
	})
	k := kernel.New(logger)
	k.Register(d)
	k.Register(a)
	if err := k.Start(); err != nil {
		t.Fatalf("start: %v", err)
	}
	t.Cleanup(func() { _ = k.Stop() })
	return a, a.Handler(), a.ProtectedHandler()
}

func TestTokenLifetimesDefault(t *testing.T) {
	_, h, _ := setupAuthWithExpiry(t, 0, 0) // zero → defaults
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"defexpiry@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: expected 201, got %d", regW.Code)
	}
	var resp map[string]any
	if err := json.NewDecoder(regW.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	expiresIn, ok := resp["expires_in"].(float64)
	if !ok {
		t.Fatalf("missing expires_in in response: %v", resp)
	}
	// Default is 24h = 86400s
	if int(expiresIn) != 86400 {
		t.Errorf("expected expires_in=86400, got %v", expiresIn)
	}
	expiresAt, ok := resp["expires_at"].(string)
	if !ok || expiresAt == "" {
		t.Fatalf("missing or empty expires_at in response: %v", resp)
	}
}

func TestTokenLifetimesCustom(t *testing.T) {
	_, h, _ := setupAuthWithExpiry(t, 5*time.Minute, 48*time.Hour)
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"custexpiry@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: expected 201, got %d", regW.Code)
	}
	var resp map[string]any
	if err := json.NewDecoder(regW.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	expiresIn, _ := resp["expires_in"].(float64)
	if int(expiresIn) != 300 {
		t.Errorf("expected expires_in=300 (5m), got %v", expiresIn)
	}
}

func TestTokenExpiryResponse(t *testing.T) {
	_, h, _ := setupAuthWithExpiry(t, 2*time.Hour, 30*24*time.Hour)
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"expiryresp@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: expected 201, got %d", regW.Code)
	}
	var resp map[string]any
	if err := json.NewDecoder(regW.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}

	// expires_in must be 7200 (2h)
	expiresIn, _ := resp["expires_in"].(float64)
	if int(expiresIn) != 7200 {
		t.Errorf("expected expires_in=7200, got %v", expiresIn)
	}

	// expires_at must be parseable RFC3339 and approximately 2h from now
	expiresAt, _ := resp["expires_at"].(string)
	parsed, err := time.Parse(time.RFC3339, expiresAt)
	if err != nil {
		t.Fatalf("invalid expires_at format %q: %v", expiresAt, err)
	}
	diff := time.Until(parsed)
	if diff < time.Hour || diff > 3*time.Hour {
		t.Errorf("expires_at not ~2h from now: diff=%v", diff)
	}
}

func TestTokenExpiryInRefreshResponse(t *testing.T) {
	_, h, _ := setupAuthWithExpiry(t, 30*time.Minute, 24*time.Hour)
	// Register
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"refexpiry@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: %d", regW.Code)
	}
	var regResp map[string]any
	_ = json.NewDecoder(regW.Body).Decode(&regResp)
	rt, _ := regResp["refresh_token"].(string)

	// Refresh
	rfReq := httptest.NewRequest("POST", "/api/auth/refresh",
		strings.NewReader(`{"refresh_token":"`+rt+`"}`))
	rfReq.Header.Set("Content-Type", "application/json")
	rfW := httptest.NewRecorder()
	h.ServeHTTP(rfW, rfReq)
	if rfW.Code != http.StatusOK {
		t.Fatalf("refresh: expected 200, got %d: %s", rfW.Code, rfW.Body.String())
	}
	var rfResp map[string]any
	_ = json.NewDecoder(rfW.Body).Decode(&rfResp)
	expiresIn, _ := rfResp["expires_in"].(float64)
	if int(expiresIn) != 1800 {
		t.Errorf("refresh: expected expires_in=1800 (30m), got %v", expiresIn)
	}
	if _, ok := rfResp["expires_at"].(string); !ok {
		t.Error("refresh: missing expires_at")
	}
}

// --- e50s03: Refresh token revocation ---

func TestTokenRevocation(t *testing.T) {
	_, h, ph := setupAuthWithExpiry(t, 24*time.Hour, 30*24*time.Hour)

	// Register
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"revoke@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	if regW.Code != http.StatusCreated {
		t.Fatalf("register: %d", regW.Code)
	}
	var regResp map[string]any
	_ = json.NewDecoder(regW.Body).Decode(&regResp)
	rt, _ := regResp["refresh_token"].(string)
	at, _ := regResp["token"].(string)

	// logout-all
	laReq := httptest.NewRequest("POST", "/api/auth/logout-all", nil)
	laReq.Header.Set("Authorization", "Bearer "+at)
	laW := httptest.NewRecorder()
	ph.ServeHTTP(laW, laReq)
	if laW.Code != http.StatusOK {
		t.Fatalf("logout-all: expected 200, got %d: %s", laW.Code, laW.Body.String())
	}

	// Subsequent refresh with old token must fail
	rfReq := httptest.NewRequest("POST", "/api/auth/refresh",
		strings.NewReader(`{"refresh_token":"`+rt+`"}`))
	rfReq.Header.Set("Content-Type", "application/json")
	rfW := httptest.NewRecorder()
	h.ServeHTTP(rfW, rfReq)
	if rfW.Code != http.StatusUnauthorized {
		t.Fatalf("refresh after logout-all: expected 401, got %d: %s", rfW.Code, rfW.Body.String())
	}
}

func TestLogoutAllMultipleTokens(t *testing.T) {
	_, h, ph := setupAuthWithExpiry(t, 24*time.Hour, 30*24*time.Hour)

	// Register
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"multirevoke@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	var regResp map[string]any
	_ = json.NewDecoder(regW.Body).Decode(&regResp)
	at, _ := regResp["token"].(string)
	rt1, _ := regResp["refresh_token"].(string)

	// Login again to get second refresh token
	loginReq := httptest.NewRequest("POST", "/api/auth/login",
		strings.NewReader(`{"email":"multirevoke@test.com","password":"secret123"}`))
	loginReq.Header.Set("Content-Type", "application/json")
	loginW := httptest.NewRecorder()
	h.ServeHTTP(loginW, loginReq)
	var loginResp map[string]any
	_ = json.NewDecoder(loginW.Body).Decode(&loginResp)
	rt2, _ := loginResp["refresh_token"].(string)

	// logout-all
	laReq := httptest.NewRequest("POST", "/api/auth/logout-all", nil)
	laReq.Header.Set("Authorization", "Bearer "+at)
	laW := httptest.NewRecorder()
	ph.ServeHTTP(laW, laReq)
	if laW.Code != http.StatusOK {
		t.Fatalf("logout-all: %d", laW.Code)
	}

	// Both refresh tokens must be invalidated
	for _, rt := range []string{rt1, rt2} {
		rfReq := httptest.NewRequest("POST", "/api/auth/refresh",
			strings.NewReader(`{"refresh_token":"`+rt+`"}`))
		rfReq.Header.Set("Content-Type", "application/json")
		rfW := httptest.NewRecorder()
		h.ServeHTTP(rfW, rfReq)
		if rfW.Code != http.StatusUnauthorized {
			t.Errorf("refresh %q after logout-all: expected 401, got %d", rt, rfW.Code)
		}
	}
}

func TestLogoutAllUnauthenticated(t *testing.T) {
	_, _, ph := setupAuthWithExpiry(t, 24*time.Hour, 30*24*time.Hour)
	req := httptest.NewRequest("POST", "/api/auth/logout-all", nil)
	w := httptest.NewRecorder()
	ph.ServeHTTP(w, req)
	if w.Code != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", w.Code)
	}
}

func TestLogoutAllAccessTokenStillValid(t *testing.T) {
	_, h, ph := setupAuthWithExpiry(t, 24*time.Hour, 30*24*time.Hour)

	// Register
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"accessvalid@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	var regResp map[string]any
	_ = json.NewDecoder(regW.Body).Decode(&regResp)
	at, _ := regResp["token"].(string)

	// logout-all
	laReq := httptest.NewRequest("POST", "/api/auth/logout-all", nil)
	laReq.Header.Set("Authorization", "Bearer "+at)
	laW := httptest.NewRecorder()
	ph.ServeHTTP(laW, laReq)
	if laW.Code != http.StatusOK {
		t.Fatalf("logout-all: %d", laW.Code)
	}

	// Access token must still work for protected endpoints
	meReq := httptest.NewRequest("GET", "/api/auth/me", nil)
	meReq.Header.Set("Authorization", "Bearer "+at)
	meW := httptest.NewRecorder()
	ph.ServeHTTP(meW, meReq)
	if meW.Code != http.StatusOK {
		t.Fatalf("me after logout-all: expected 200, got %d: %s", meW.Code, meW.Body.String())
	}
}

func TestLogoutAllIdempotentNoTokens(t *testing.T) {
	_, h, ph := setupAuthWithExpiry(t, 24*time.Hour, 30*24*time.Hour)

	// Register
	regReq := httptest.NewRequest("POST", "/api/auth/register",
		strings.NewReader(`{"email":"idempotent@test.com","password":"secret123"}`))
	regReq.Header.Set("Content-Type", "application/json")
	regW := httptest.NewRecorder()
	h.ServeHTTP(regW, regReq)
	var regResp map[string]any
	_ = json.NewDecoder(regW.Body).Decode(&regResp)
	at, _ := regResp["token"].(string)

	// Call logout-all twice — both must return 200
	for i := 0; i < 2; i++ {
		laReq := httptest.NewRequest("POST", "/api/auth/logout-all", nil)
		laReq.Header.Set("Authorization", "Bearer "+at)
		laW := httptest.NewRecorder()
		ph.ServeHTTP(laW, laReq)
		if laW.Code != http.StatusOK {
			t.Fatalf("logout-all call %d: expected 200, got %d", i+1, laW.Code)
		}
	}
}
