#!/usr/bin/env bash
# gen-mcp-configs.sh — generate per-client MCP adapter configs from the single
# canonical source, .mcp.json (e90s05).
#
# Canonical:  .mcp.json               (Claude Code project MCP config — edit THIS)
# Generated:  .claude/mcp.json        (byte-identical Claude-format mirror)
#             opencode.jsonc          (opencode schema: mcpServers -> mcp, http -> remote)
#
# opencode.json (the rich full opencode config: agents, commands, permissions)
# is hand-maintained and NOT generated — only its `mcp` block should mirror this,
# which is enforced by the doc/config reviewer, not this script.
#
# Usage:
#   scripts/gen-mcp-configs.sh            regenerate the adapter files in place
#   scripts/gen-mcp-configs.sh --check    exit 1 if any generated file is stale
#                                         (no writes) — for CI
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

command -v jq >/dev/null || { echo "ERROR: jq is required" >&2; exit 2; }

CANON=".mcp.json"
CLAUDE_OUT=".claude/mcp.json"
OPENCODE_OUT="opencode.jsonc"

# --- Claude mirror: canonical JSON, jq-normalized formatting. -----------------
render_claude() { jq -S . "$CANON"; }

# Servers that are NOT agent-universal — they only work under Claude, so they
# are emitted to the Claude-format files but excluded from other adapters.
CLAUDE_ONLY='["claude_design"]'

# --- opencode adapter: transform Claude schema -> opencode schema. ------------
#   mcpServers        -> mcp   (minus CLAUDE_ONLY servers)
#   {command,args}    -> {type:"local",  command:[command, ...args]}
#   {type:http,url}   -> {type:"remote", url, headers?}
render_opencode() {
  printf '// GENERATED by scripts/gen-mcp-configs.sh from .mcp.json — DO NOT EDIT.\n'
  printf '// Edit .mcp.json (the canonical source), then run scripts/gen-mcp-configs.sh.\n'
  printf '// Claude-only servers (%s) are intentionally omitted here.\n' "$CLAUDE_ONLY"
  jq -S --argjson claude_only "$CLAUDE_ONLY" '{
    "$schema": "https://opencode.ai/config.json",
    mcp: (.mcpServers | to_entries
      | map(select(.key as $k | ($claude_only | index($k)) | not))
      | map({
      key: .key,
      value: (
        if (.value.command // null) != null then
          { type: "local", command: ([.value.command] + (.value.args // [])) }
        else
          ({ type: "remote", url: .value.url }
           + (if (.value.headers // null) != null then { headers: .value.headers } else {} end))
        end
      )
    }) | from_entries)
  }' "$CANON"
}

write_or_check() {
  local target="$1" rendered="$2"
  if [ "${MODE:-write}" = "check" ]; then
    if ! diff -q <(printf '%s\n' "$rendered") "$target" >/dev/null 2>&1; then
      echo "STALE: $target is out of sync with $CANON" >&2
      diff <(printf '%s\n' "$rendered") "$target" >&2 || true
      return 1
    fi
    echo "ok: $target"
  else
    mkdir -p "$(dirname "$target")"
    printf '%s\n' "$rendered" > "$target"
    echo "wrote: $target"
  fi
}

MODE=write
[ "${1:-}" = "--check" ] && MODE=check

rc=0
write_or_check "$CLAUDE_OUT"   "$(render_claude)"   || rc=1
write_or_check "$OPENCODE_OUT" "$(render_opencode)" || rc=1

if [ "$MODE" = "check" ] && [ "$rc" -ne 0 ]; then
  echo "" >&2
  echo "MCP adapter configs are stale. Run: scripts/gen-mcp-configs.sh" >&2
fi
exit "$rc"
