#!/usr/bin/env bash
set -euo pipefail

root=$(git rev-parse --show-toplevel)
cd "$root"
strict=false
for arg in "$@"; do
  case "$arg" in
    --json) json_mode=true ;;
    --strict) strict=true ;;
    *) echo "usage: $0 [--json] [--strict]" >&2; exit 2 ;;
  esac
done

python3 - "$root" "$strict" <<'PY'
from __future__ import annotations
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

root = Path(sys.argv[1])
strict = sys.argv[2].lower() == "true"
source_roots = [root / "components", root / "kernel", root / "internal", root / "ui", root / "tests", root / "main.go", root / "adapters.go", root / "scripts"]
extensions = {".go", ".ts", ".tsx", ".js", ".css", ".py", ".sh"}
tag_re = re.compile(r"(?://|#|<!--)\s*story:\s*(e\d+s\d+)")
story_re = re.compile(r"^\s*- id:\s*(e\d+s\d+)\s*$", re.M)
title_re = re.compile(r"^\s+title:\s*[\"']?(.+?)[\"']?\s*$", re.M)
stories: dict[str, dict] = {}

for manifest in sorted((root / "specs" / "epics").rglob("epic.yaml")):
    text = manifest.read_text(errors="replace")
    ids = list(story_re.finditer(text))
    for idx, match in enumerate(ids):
        story_id = match.group(1)
        end = ids[idx + 1].start() if idx + 1 < len(ids) else len(text)
        body = text[match.start():end]
        title_match = title_re.search(body)
        stories.setdefault(story_id, {"story_id": story_id, "title": title_match.group(1).strip() if title_match else story_id, "files": [], "tests": []})

for root_entry in source_roots:
    paths = [root_entry] if root_entry.is_file() else (root_entry.rglob("*") if root_entry.is_dir() else [])
    for path in paths:
        if not path.is_file() or path.suffix not in extensions:
            continue
        if any(part in {".git", "node_modules", "dist", "build", ".bigpowers"} for part in path.parts):
            continue
        text = path.read_text(errors="replace")
        ids = set(tag_re.findall(text))
        for story_id in ids:
            if story_id not in stories:
                stories[story_id] = {"story_id": story_id, "title": story_id, "files": [], "tests": [], "orphan": True}
            rel = path.relative_to(root).as_posix()
            stories[story_id]["files"].append(rel)
            if "test" in path.name.lower() or ".spec." in path.name:
                stories[story_id]["tests"].append(rel)

for story in stories.values():
    story["files"] = sorted(set(story["files"]))
    story["tests"] = sorted(set(story["tests"]))
    story["status"] = "Covered" if story["files"] else "Dark"

ordered = [stories[key] for key in sorted(stories)]
covered = sum(item["status"] == "Covered" for item in ordered)
dark = len(ordered) - covered
matrix = {
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "source": ["specs/release-plan.yaml", "specs/epics/**/epic.yaml", "story tags in source/test files"],
    "stories": ordered,
    "summary": {"total": len(ordered), "covered": covered, "dark": dark, "orphans": sum(bool(item.get("orphan")) for item in ordered)},
    "oracle_stats": {"explicit_tag_links": covered, "heuristic_links": 0, "heuristic_ratio": 0.0},
}

specs = root / "specs"
specs.mkdir(exist_ok=True)
(specs / "traceability-matrix.json").write_text(json.dumps(matrix, indent=2) + "\n")
lines = [
    "# Traceability Matrix",
    "",
    f"Generated: {matrix['generated_at']}",
    "",
    "## Story Coverage",
    "",
    "| Story | Title | Files | Tests | Status |",
    "|---|---|---:|---:|---|",
]
for item in ordered:
    lines.append(f"| {item['story_id']} | {item['title']} | {len(item['files'])} | {len(item['tests'])} | {item['status']} |")
lines += ["", "## Gaps", ""]
for item in ordered:
    if item["status"] == "Dark":
        lines.append(f"- {item['story_id']}: no story-tagged implementation files")
if not any(item["status"] == "Dark" for item in ordered):
    lines.append("None.")
lines += ["", "## Summary", "", f"Stories: {covered} covered / {dark} dark / {len(ordered)} total.", ""]
(specs / "TRACEABILITY_LATEST.md").write_text("\n".join(lines))

wiki = specs / "codebase-wiki"
wiki.mkdir(exist_ok=True)
(wiki / "index.md").write_text("# Codebase Wiki\n\nGenerated by `scripts/trace-stories.sh`.\n\n- [Traceability](traceability.md)\n")
(wiki / "traceability.md").write_text("\n".join(lines))

if strict and dark:
    print(f"trace-stories: FAIL ({dark} dark stories)", file=sys.stderr)
    raise SystemExit(1)
print(json.dumps({"matrix": str(specs / "traceability-matrix.json"), "covered": covered, "dark": dark, "total": len(ordered)}))
PY
