package projects

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/danielvm/bigbase/components/auth"
	"github.com/danielvm/bigbase/kernel"
)

const version = "0.1.0"

// projectsMigration and environmentsMigration use SQL accepted by both the
// SQLite and PostgreSQL DBer implementations. IDs are generated by the
// component so neither driver needs an engine-specific identity type.
const projectsMigration = `CREATE TABLE IF NOT EXISTS projects (
	id TEXT PRIMARY KEY,
	org_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (org_id, name)
)`

const environmentsMigration = `CREATE TABLE IF NOT EXISTS project_environments (
	id TEXT PRIMARY KEY,
	project_id TEXT NOT NULL,
	slug TEXT NOT NULL,
	name TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (project_id, slug),
	FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
)`

var (
	ErrOrganizationRequired = errors.New("organization required")
	ErrProjectNotFound      = errors.New("project not found")
	ErrEnvironmentNotFound  = errors.New("environment not found")
	ErrProjectHasSites      = errors.New("project has attached sites")
)

type Project struct {
	ID        string `json:"id"`
	OrgID     int64  `json:"org_id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Environment struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type DBer = kernel.DBer

type Options struct {
	DB     DBer
	Logger kernel.Logger
}

type Projects struct {
	db     DBer
	logger kernel.Logger
}

var _ kernel.Component = (*Projects)(nil)

func New(opts Options) *Projects {
	logger := opts.Logger
	if logger == nil {
		logger = kernel.NoopLogger{}
	}
	return &Projects{db: opts.DB, logger: logger}
}

func (p *Projects) Name() string                                    { return "projects" }
func (p *Projects) Version() string                                 { return version }
func (p *Projects) Dependencies() []string                          { return []string{"db"} }
func (p *Projects) Init(_ *kernel.Context, _ json.RawMessage) error { return nil }

func (p *Projects) Start(_ *kernel.Context) error {
	if p.db == nil {
		return errors.New("projects: DB is required")
	}
	if err := p.db.Migrate(projectsMigration); err != nil {
		return fmt.Errorf("migrate projects: %w", err)
	}
	if err := p.db.Migrate(environmentsMigration); err != nil {
		return fmt.Errorf("migrate project environments: %w", err)
	}
	if err := p.db.Migrate(`CREATE INDEX IF NOT EXISTS idx_projects_org_id ON projects(org_id)`); err != nil {
		return fmt.Errorf("migrate project org index: %w", err)
	}
	if err := p.db.Migrate(`CREATE INDEX IF NOT EXISTS idx_project_environments_project_id ON project_environments(project_id)`); err != nil {
		return fmt.Errorf("migrate environment project index: %w", err)
	}
	// Sites owns its table and starts after this component. Apply the column
	// here when an existing sites table is already present; Sites.Start repeats
	// this idempotently for fresh installations.
	_ = p.db.Migrate(`ALTER TABLE sites ADD COLUMN project_id TEXT REFERENCES projects(id)`)
	_ = p.db.Migrate(`CREATE INDEX IF NOT EXISTS idx_sites_project_id ON sites(project_id)`)
	return nil
}

func (p *Projects) Stop(_ *kernel.Context) error { return nil }

func orgIDFromContext(ctx context.Context) (int64, error) {
	orgID, ok := auth.OrgIDFromContext(ctx)
	if !ok || orgID <= 0 {
		return 0, ErrOrganizationRequired
	}
	return orgID, nil
}

func validateName(value, field string) (string, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return "", fmt.Errorf("%s is required", field)
	}
	if len(value) > 200 {
		return "", fmt.Errorf("%s is too long", field)
	}
	return value, nil
}

func (p *Projects) CreateProject(ctx context.Context, name string) (*Project, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	name, err = validateName(name, "name")
	if err != nil {
		return nil, err
	}
	id, err := kernel.GenerateID()
	if err != nil {
		return nil, fmt.Errorf("generate project id: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339)
	if _, err := p.db.ExecContext(ctx,
		`INSERT INTO projects (id, org_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)`,
		id, orgID, name, now, now); err != nil {
		return nil, fmt.Errorf("create project: %w", err)
	}
	return p.getProject(ctx, id, orgID)
}

func (p *Projects) ListProjects(ctx context.Context) ([]Project, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := p.db.QueryContext(ctx,
		`SELECT id, org_id, name, created_at, updated_at FROM projects WHERE org_id = ? ORDER BY name, id`, orgID)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	defer func() { _ = rows.Close() }()
	result := make([]Project, 0)
	for rows.Next() {
		var project Project
		if err := rows.Scan(&project.ID, &project.OrgID, &project.Name, &project.CreatedAt, &project.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan project: %w", err)
		}
		result = append(result, project)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list projects rows: %w", err)
	}
	return result, nil
}

func (p *Projects) GetProject(ctx context.Context, id string) (*Project, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return p.getProject(ctx, id, orgID)
}

func (p *Projects) getProject(ctx context.Context, id string, orgID int64) (*Project, error) {
	var project Project
	err := p.db.QueryRowContext(ctx,
		`SELECT id, org_id, name, created_at, updated_at FROM projects WHERE id = ? AND org_id = ?`, id, orgID).
		Scan(&project.ID, &project.OrgID, &project.Name, &project.CreatedAt, &project.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrProjectNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	return &project, nil
}

func (p *Projects) UpdateProject(ctx context.Context, id, name string) (*Project, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	name, err = validateName(name, "name")
	if err != nil {
		return nil, err
	}
	result, err := p.db.ExecContext(ctx,
		`UPDATE projects SET name = ?, updated_at = ? WHERE id = ? AND org_id = ?`,
		name, time.Now().UTC().Format(time.RFC3339), id, orgID)
	if err != nil {
		return nil, fmt.Errorf("update project: %w", err)
	}
	if n, _ := result.RowsAffected(); n == 0 {
		return nil, ErrProjectNotFound
	}
	return p.getProject(ctx, id, orgID)
}

func (p *Projects) DeleteProject(ctx context.Context, id string) error {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return err
	}
	if _, err := p.getProject(ctx, id, orgID); err != nil {
		return err
	}
	var attached int
	if err := p.db.QueryRowContext(ctx, `SELECT COUNT(1) FROM sites WHERE project_id = ?`, id).Scan(&attached); err != nil && !missingSitesTable(err) {
		return fmt.Errorf("check project attachments: %w", err)
	}
	if attached > 0 {
		return ErrProjectHasSites
	}
	result, err := p.db.ExecContext(ctx, `DELETE FROM projects WHERE id = ? AND org_id = ?`, id, orgID)
	if err != nil {
		return fmt.Errorf("delete project: %w", err)
	}
	if n, _ := result.RowsAffected(); n == 0 {
		return ErrProjectNotFound
	}
	return nil
}

func missingSitesTable(err error) bool {
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "no such table") || strings.Contains(message, "undefined table") || strings.Contains(message, "does not exist")
}

func (p *Projects) ListEnvironments(ctx context.Context, projectID string) ([]Environment, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := p.getProject(ctx, projectID, orgID); err != nil {
		return nil, err
	}
	rows, err := p.db.QueryContext(ctx,
		`SELECT e.id, e.project_id, e.slug, e.name, e.created_at, e.updated_at
		 FROM project_environments e JOIN projects p ON p.id = e.project_id
		 WHERE e.project_id = ? AND p.org_id = ? ORDER BY e.name, e.id`, projectID, orgID)
	if err != nil {
		return nil, fmt.Errorf("list environments: %w", err)
	}
	defer func() { _ = rows.Close() }()
	result := make([]Environment, 0)
	for rows.Next() {
		var environment Environment
		if err := rows.Scan(&environment.ID, &environment.ProjectID, &environment.Slug, &environment.Name, &environment.CreatedAt, &environment.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan environment: %w", err)
		}
		result = append(result, environment)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list environments rows: %w", err)
	}
	return result, nil
}

func (p *Projects) CreateEnvironment(ctx context.Context, projectID, slug, name string) (*Environment, error) {
	orgID, err := orgIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := p.getProject(ctx, projectID, orgID); err != nil {
		return nil, err
	}
	slug, err = validateSlug(slug)
	if err != nil {
		return nil, err
	}
	name, err = validateName(name, "name")
	if err != nil {
		return nil, err
	}
	id, err := kernel.GenerateID()
	if err != nil {
		return nil, fmt.Errorf("generate environment id: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339)
	if _, err := p.db.ExecContext(ctx,
		`INSERT INTO project_environments (id, project_id, slug, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)`,
		id, projectID, slug, name, now, now); err != nil {
		return nil, fmt.Errorf("create environment: %w", err)
	}
	return p.getEnvironment(ctx, id, projectID, orgID)
}

func validateSlug(slug string) (string, error) {
	slug = strings.TrimSpace(strings.ToLower(slug))
	if slug == "" {
		return "", errors.New("slug is required")
	}
	if len(slug) > 100 {
		return "", errors.New("slug is too long")
	}
	for _, r := range slug {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' && r != '_' {
			return "", errors.New("slug must contain only lowercase letters, numbers, hyphens, and underscores")
		}
	}
	return slug, nil
}

func (p *Projects) getEnvironment(ctx context.Context, id, projectID string, orgID int64) (*Environment, error) {
	var environment Environment
	err := p.db.QueryRowContext(ctx,
		`SELECT e.id, e.project_id, e.slug, e.name, e.created_at, e.updated_at
		 FROM project_environments e JOIN projects p ON p.id = e.project_id
		 WHERE e.id = ? AND e.project_id = ? AND p.org_id = ?`, id, projectID, orgID).
		Scan(&environment.ID, &environment.ProjectID, &environment.Slug, &environment.Name, &environment.CreatedAt, &environment.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrEnvironmentNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get environment: %w", err)
	}
	return &environment, nil
}

// EnsureSiteProject attaches one project and its production environment to a
// site. It is the seam consumed by Sites; orgID comes from the persisted Site,
// not from request input, so compatibility migration preserves ownership.
func (p *Projects) EnsureSiteProject(ctx context.Context, siteID, siteName string, orgID int64) (string, error) {
	return p.ensureSiteProject(ctx, siteID, siteName, orgID, false)
}

func (p *Projects) ensureSiteProject(ctx context.Context, siteID, siteName string, orgID int64, compatibility bool) (string, error) {
	var projectID sql.NullString
	if err := p.db.QueryRowContext(ctx, `SELECT project_id FROM sites WHERE id = ?`, siteID).Scan(&projectID); err == nil && projectID.Valid && projectID.String != "" {
		return projectID.String, nil
	}
	if siteID == "" {
		return "", errors.New("site id is required")
	}
	if siteName == "" {
		siteName = siteID
	}
	name := siteName
	if compatibility {
		name = fmt.Sprintf("Compatibility - %s (%s)", siteName, siteID)
	}
	projectIDValue, err := kernel.GenerateID()
	if err != nil {
		return "", fmt.Errorf("generate compatibility project id: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339)
	if _, err := p.db.ExecContext(ctx,
		`INSERT INTO projects (id, org_id, name, created_at, updated_at) VALUES (?, ?, ?, ?, ?)`,
		projectIDValue, orgID, name, now, now); err != nil {
		return "", fmt.Errorf("create site project: %w", err)
	}
	environmentID, err := kernel.GenerateID()
	if err != nil {
		return "", fmt.Errorf("generate production environment id: %w", err)
	}
	if _, err := p.db.ExecContext(ctx,
		`INSERT INTO project_environments (id, project_id, slug, name, created_at, updated_at) VALUES (?, ?, 'production', 'Production', ?, ?)`,
		environmentID, projectIDValue, now, now); err != nil {
		return "", fmt.Errorf("create production environment: %w", err)
	}
	if _, err := p.db.ExecContext(ctx, `UPDATE sites SET project_id = ? WHERE id = ? AND project_id IS NULL`, projectIDValue, siteID); err != nil {
		return "", fmt.Errorf("attach site project: %w", err)
	}
	return projectIDValue, nil
}

// MigrateSiteAttachments creates one compatibility Project and production
// Environment for every existing Site without changing site_env_vars.
func (p *Projects) MigrateSiteAttachments(ctx context.Context) error {
	rows, err := p.db.QueryContext(ctx, `SELECT id, name, org_id FROM sites WHERE project_id IS NULL`)
	if err != nil {
		if missingSitesTable(err) {
			return nil
		}
		return fmt.Errorf("list sites for project migration: %w", err)
	}
	type siteRow struct {
		id    string
		name  string
		orgID int64
	}
	var sites []siteRow
	for rows.Next() {
		var site siteRow
		if err := rows.Scan(&site.id, &site.name, &site.orgID); err != nil {
			_ = rows.Close()
			return fmt.Errorf("scan site for project migration: %w", err)
		}
		sites = append(sites, site)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return fmt.Errorf("read sites for project migration: %w", err)
	}
	_ = rows.Close()
	for _, site := range sites {
		if _, err := p.ensureSiteProject(ctx, site.id, site.name, site.orgID, true); err != nil {
			return err
		}
	}
	return nil
}

func (p *Projects) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/api/projects", p.handleProjects)
	mux.HandleFunc("/api/projects/", p.handleProjectByID)
	return mux
}

func (p *Projects) handleProjects(w http.ResponseWriter, r *http.Request) {
	if _, err := orgIDFromContext(r.Context()); err != nil {
		writeProjectError(w, err)
		return
	}
	switch r.Method {
	case http.MethodGet:
		projects, err := p.ListProjects(r.Context())
		if err != nil {
			writeProjectError(w, err)
			return
		}
		kernel.WriteJSON(w, http.StatusOK, map[string]any{"data": projects})
	case http.MethodPost:
		var req struct {
			Name string `json:"name"`
		}
		r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeProjectError(w, errors.New("invalid json"))
			return
		}
		project, err := p.CreateProject(r.Context(), req.Name)
		if err != nil {
			writeProjectError(w, err)
			return
		}
		kernel.WriteJSON(w, http.StatusCreated, map[string]any{"data": project})
	default:
		kernel.WriteJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
	}
}

func (p *Projects) handleProjectByID(w http.ResponseWriter, r *http.Request) {
	parts := strings.Split(strings.Trim(strings.TrimPrefix(r.URL.Path, "/api/projects/"), "/"), "/")
	if len(parts) == 0 || parts[0] == "" {
		writeProjectError(w, ErrProjectNotFound)
		return
	}
	id := parts[0]
	if len(parts) == 2 && parts[1] == "environments" {
		p.handleEnvironments(w, r, id)
		return
	}
	if len(parts) != 1 {
		writeProjectError(w, ErrProjectNotFound)
		return
	}
	var project *Project
	var err error
	switch r.Method {
	case http.MethodGet:
		project, err = p.GetProject(r.Context(), id)
	case http.MethodPatch, http.MethodPut:
		var req struct {
			Name string `json:"name"`
		}
		r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
		if decodeErr := json.NewDecoder(r.Body).Decode(&req); decodeErr != nil {
			writeProjectError(w, errors.New("invalid json"))
			return
		}
		project, err = p.UpdateProject(r.Context(), id, req.Name)
	case http.MethodDelete:
		err = p.DeleteProject(r.Context(), id)
		if err == nil {
			kernel.WriteJSON(w, http.StatusNoContent, nil)
			return
		}
	default:
		kernel.WriteJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}
	if err != nil {
		writeProjectError(w, err)
		return
	}
	kernel.WriteJSON(w, http.StatusOK, map[string]any{"data": project})
}

func (p *Projects) handleEnvironments(w http.ResponseWriter, r *http.Request, projectID string) {
	switch r.Method {
	case http.MethodGet:
		environments, err := p.ListEnvironments(r.Context(), projectID)
		if err != nil {
			writeProjectError(w, err)
			return
		}
		kernel.WriteJSON(w, http.StatusOK, map[string]any{"data": environments})
	case http.MethodPost:
		var req struct {
			Slug string `json:"slug"`
			Name string `json:"name"`
		}
		r.Body = http.MaxBytesReader(w, r.Body, 1<<20)
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeProjectError(w, errors.New("invalid json"))
			return
		}
		environment, err := p.CreateEnvironment(r.Context(), projectID, req.Slug, req.Name)
		if err != nil {
			writeProjectError(w, err)
			return
		}
		kernel.WriteJSON(w, http.StatusCreated, map[string]any{"data": environment})
	default:
		kernel.WriteJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
	}
}

func writeProjectError(w http.ResponseWriter, err error) {
	status := http.StatusInternalServerError
	message := "internal error"
	switch {
	case errors.Is(err, ErrOrganizationRequired):
		status, message = http.StatusForbidden, "organization required"
	case errors.Is(err, ErrProjectNotFound), errors.Is(err, ErrEnvironmentNotFound):
		status, message = http.StatusNotFound, "not found"
	case errors.Is(err, ErrProjectHasSites):
		status, message = http.StatusConflict, "project has attached sites"
	case strings.Contains(err.Error(), "required"), strings.Contains(err.Error(), "invalid"), strings.Contains(err.Error(), "too long"), strings.Contains(err.Error(), "only lowercase"):
		status, message = http.StatusBadRequest, err.Error()
	case strings.Contains(strings.ToLower(err.Error()), "unique") || strings.Contains(strings.ToLower(err.Error()), "constraint"):
		status, message = http.StatusConflict, "resource already exists"
	}
	kernel.WriteJSON(w, status, map[string]string{"error": message})
}
